### ISSUE TITLE
Nav links keep subdomain and thus break

### ISSUE THREAD

**Issue by bkimminich** [OWASP/video-portal#2]
## How to reproduce
1. Go to https://videos.owasp.org/
2. Open any top nav menu and choose a link (e.g. _Projects_ > _Juice Shop_)
3. Get a `404` (in above example b/c it tried to go to https://videos.owasp.org/www-project-juice-shop)

![image](https://user-images.githubusercontent.com/3531020/72710762-0e410080-3b68-11ea-8651-b0943e7f6f4d.png)

**Comment by jmarcil** [comment]
fixed with #3
